POST http://localhost:9201/labels/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "autocomplete": "sony"
    }
  },
  "aggs": {
    "root": {
      "nested": {
        "path": "tags"
      },
      "aggs": {
        "group": {
          "terms": {
            "field": "tags.name",
            "min_doc_count": 5
          }

        }
      }
    }
   }
}

###
