POST http://10.10.8.107:9200/playlists/_search
Content-Type: application/json

{
    "query": {
        "multi_match": {
            "query": "Karl Popper philosophy",
            "fields": [
                "name",
                "description"
            ]
        }
    },
    "highlight": {
        "fields": {
            "description": {}
        }
    }
}

###
