POST http://localhost:9201/labels/_search
Content-Type: application/json

{
    "sort": [
        "name"
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "labelcode": "LC1000250"
                    }
                }
            ]
        }
    }
}

###
