POST http://localhost:9200/releases/_search
Content-Type: application/json

{
    "sort": [
        "name"
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "name": "tetra"
                    }
                }
            ]
        }
    }
}

###
