POST http://localhost:9201/_search
Content-Type: application/json



{
    "query": {
        "bool": {
            "must": {
                "multi_match" : {
                  "query":    "Uwe Schmidt",
                  "type":       "best_fields",
                  "fields": [
                      "autocomplete^3",
                      "name^3",
                      "*_name",
                      "aliases.name"
                      ],
                  "operator":   "and"
                },
                "term": {
                    "tags": "foo"
                }
            },
            "filter": {
                "term": {
                    "country": "DE"
                }
            }
        }
    }
}



//{
//  "query": {
//    "multi_match" : {
//      "query":    "Uwe Schmidt",
//      "type":       "best_fields",
//      "fields": [
//          "autocomplete^3",
//          "name^3",
//          "*_name",
//          "aliases.name"
//          ],
//      "operator":   "and"
//    }
//  }
//}

//{
//    "query": {
//        "match" : {
//            "name.edgengram" : {
//                "query": "america the",
//                "operator" : "and"
//            }
//        }
//    }
//}

//{
//    "query": {
//        "match" : {
//            "name.edgengram" : {
//                "query": "america",
//                "fuzziness": "AUTO",
//                "operator" : "and"
//            }
//        }
//    },
//    "highlight" : {
//        "fields" : {
//            "name" : {"type" : "plain"}
//        }
//    }
//}

//{
//    "query": {
//        "match" : {
//            "name" : {
//                "query": "america the",
//                "operator" : "and"
//            }
//        }
//    }
//}

###
