PUT  http://10.35.30.231:9200/_cluster/settings
Content-Type: application/json

{
  "transient": {
    "cluster.routing.allocation.disk.watermark.low": "2mb",
    "cluster.routing.allocation.disk.watermark.high": "1mb",
    "cluster.routing.allocation.disk.watermark.flood_stage": "1mb",
    "cluster.info.update.interval": "10s"
  }
}

###
