engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
  radon:
    enabled: true
  fixme:
    enabled: true


ratings:
   paths:
   - "**.js"
   - "**.py"


languages:
  JavaScript: true
  Python: true

exclude_paths:
- "bin/*"
- "conf/*"
- "doc/*"
- "**/migrations/*"
- "website/tools/*"
- "website/legacy/obp_legacy/*"
- "website/apps/nunjucks/*"
