engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  radon:
    enabled: true
  fixme:
    enabled: true
  bandit:
    enabled: true
  pylint:
    enabled: true
    plugins:
      - django

ratings:
   paths:
   - "**.js"
   - "**.vue"
   - "**.scss"
   - "**.py"
   - "**.html"

languages:
  JavaScript: true
  Python: true

exclude_paths:
- "bin/*"
- "conf/*"
- "doc/*"
- "services/*"
- "**/migrations/*"
- "website/tools/*"
- "website/legacy/*"
- "website/apps/nunjucks/*"
- "website/apps/ac_tagging/*"
- "website/apps/importer/*"
- "website/static-src/*"
- "website/**/static/*"
- "static/sass/*"
- "**/js/lib/**/*"
- "**/templates.js"
