session_name: openbroadcast_org
start_directory: ./
windows:

- window_name: dev window
  layout: tiled
  focus: true
  shell_command_before:
    - 'source ~/srv/openbroadcast.org/bin/activate'
  panes:
    - focus: true
    - shell_command:
        - cd website
        - ./manage.py runserver 0.0.0.0:8080
    - shell_command:
        - cd website
        - celery -A project worker -c 1 -Q celery -l INFO
    - shell_command:
        - cd website
        - celery -A project worker -c 2 -Q convert,grapher -l INFO
    - ./node_modules/gulp/bin/gulp.js watch
    - cd website


- window_name: services
  layout: tiled

  start_directory: website/
  shell_command_before:
    - 'source ~/srv/openbroadcast.org/bin/activate'
  panes:
    - shell_command:
        - cd ~/code/openbroadcast/pushy/server/
        - node pushy.js
    - shell_command:
        - rabbitmq-server
    - shell_command:
        - cd ~/code/openbroadcast/services/fprint-api && ~/srv/fprint-api/bin/python manage.py runserver 0.0.0.0:7777
    - shell_command:
        - cd ~/code/openbroadcast/services/playlist-mixdown-api && ~/srv/playlist-mixdown-api/bin/python manage.py runserver 0.0.0.0:7778
    - shell_command:
        - cd ~/code/openbroadcast/services/media-preflight-api && ~/srv/media-preflight-api/bin/python manage.py runserver 0.0.0.0:7779

