version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ${PWD}/docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ${PWD}/docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    restart: always
    networks:
      - obp
  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    restart: always
    networks:
      - obp
  elasticsearch:
    image: elasticsearch:6.8.20
    environment:
      - cluster.name=obp
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    ports:
      - "9200:9200"
    restart: always
    networks:
      - obp
  pushy:
    build:
      context: .
      dockerfile: ./docker/pushy/Dockerfile
    ports:
      - "8180:8000"
    restart: always
    networks:
      - obp

volumes:
  obp:

networks:
  obp:
