# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcast', '0006_remove_filer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jingleset',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='abcast/station', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='station',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='abcast/station', verbose_name='Image'),
        ),
    ]
