from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r"^$",
        views.PlaylistListView.as_view(scope="public"),
        name="playlist-list",
    ),
    url(
        r"^(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/$",
        views.PlaylistDetailView.as_view(),
        name="playlist-detail-legacy",
    ),
    url(
        r"^own/$",
        views.PlaylistListView.as_view(scope="own"),
        name="playlist-list-own",
    ),
    url(
        r"^create/$",
        views.PlaylistCreateView.as_view(),
        name="playlist-create",
    ),
    url(
        r"^(?P<pk>\d+)/edit/$",
        views.PlaylistEditView.as_view(),
        name="playlist-edit-legacy",
    ),
    url(
        r"^(?P<pk>\d+)/delete/$",
        views.PlaylistDeleteView.as_view(),
        name="playlist-delete",
    ),
    url(
        r"^(?P<pk>\d+)/convert/(?P<playlist_type>[-\w]+)/$",
        views.playlist_convert,
        name="playlist-convert",
    ),
    url(
        r"^(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/(?:(?P<section>[-\w]+)/)?$",
        views.PlaylistDetailView.as_view(),
        name="playlist-detail",
    ),
    url(
        r"^edit/(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/(?:(?P<section>[-\w]+)/)?$",
        views.PlaylistEditView.as_view(),
        name="playlist-edit",
    ),
]
