version: "3"
services:
#  rabbitmq:
#    image: rabbitmq:3.9-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin
#      - RABBITMQ_DEFAULT_PASS=admin
#    volumes:
#      - ${PWD}/docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#      - ${PWD}/docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
#    restart: always
#    networks:
#      - obp
  nginx:
    container_name: nginx
    build:
      context: ${PWD}/docker/nginx/
      dockerfile: ${PWD}/docker/nginx/Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ${PWD}/website/media:/data/media
    restart: always
    networks:
      - obp
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 'obp'
      MYSQL_PASS: 'obp'
    volumes:
      - obp-mariadb:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - obp
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ${PWD}/docker/rabbitmq/
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - obp
  redis:
    container_name: redis
    image: redis:5.0.5
    ports:
      - "6380:6379"
    restart: always
    networks:
      - obp
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.8.20
    environment:
      - cluster.name=obp
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
#      - ${PWD}/data/elasticsearch:/usr/share/elasticsearch/data
      - obp-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
    networks:
      - obp
  pushy:
    container_name: pushy
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/pushy/Dockerfile
    ports:
      - "8180:8000"
    restart: always
    networks:
      - obp

volumes:
  obp:
  obp-mariadb:
  obp-elasticsearch:

networks:
  obp:
