# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("actstream", "0002_auto_20160526_1618")]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        )
    ]
